"""Tests for `caasi mapping` — run nvblox / occupancy mapping and inspect map YAML."""

from __future__ import annotations

import json
import struct

import yaml

from caasi.cli.main import app

from .conftest import all_output
from .test_ros_cmd import configure_runs, wait_for_run

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"

MAP_DATA = {
    "image": "map.png",
    "resolution": 0.05,
    "origin": [-10.0, -10.0, 0.0],
    "negate": 0,
    "occupied_thresh": 0.65,
    "free_thresh": 0.25,
    "mode": "trinary",
}


def write_png(path, width: int, height: int) -> None:
    """A header-only PNG — `mapping inspect` reads IHDR bytes, not pixels."""
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 0, 0, 0, 0)
    path.write_bytes(PNG_SIGNATURE + struct.pack(">I", len(ihdr)) + b"IHDR" + ihdr)


def write_map(tmp_path, data=None, image=None):
    data = dict(MAP_DATA if data is None else data)
    if image is not None:
        data["image"] = image
    map_yaml = tmp_path / "map.yaml"
    map_yaml.write_text(yaml.safe_dump(data), encoding="utf-8")
    return map_yaml


def test_mapping_inspect_png(runner, tmp_path):
    write_png(tmp_path / "map.png", 400, 300)
    map_yaml = write_map(tmp_path)

    result = runner.invoke(app, ["mapping", "inspect", str(map_yaml), "--json"])
    assert result.exit_code == 0, all_output(result)
    data = json.loads(result.output)
    assert data["path"] == str(map_yaml)
    assert data["image"] == str(tmp_path / "map.png")
    assert data["image_exists"] is True
    assert (data["width"], data["height"]) == (400, 300)
    assert data["resolution"] == 0.05
    assert data["origin"] == [-10.0, -10.0, 0.0]
    assert data["occupied_thresh"] == 0.65
    assert data["free_thresh"] == 0.25
    assert data["mode"] == "trinary"
    assert data["width_metres"] == 20.0
    assert data["height_metres"] == 15.0


def test_mapping_inspect_table(runner, tmp_path):
    write_png(tmp_path / "map.png", 400, 300)
    map_yaml = write_map(tmp_path)

    result = runner.invoke(app, ["mapping", "inspect", str(map_yaml)])
    assert result.exit_code == 0, all_output(result)
    assert "map.yaml" in result.output
    assert "400 × 300" in result.output
    assert "20.0 m × 15.0 m" in result.output
    assert "trinary" in result.output


def test_mapping_inspect_pgm(runner, tmp_path):
    (tmp_path / "map.pgm").write_bytes(b"P5\n# generated by map_saver\n120 90\n255\n" + b"\x00" * 64)
    map_yaml = write_map(tmp_path, image="map.pgm")

    result = runner.invoke(app, ["mapping", "inspect", str(map_yaml), "--json"])
    assert result.exit_code == 0, all_output(result)
    data = json.loads(result.output)
    assert (data["width"], data["height"]) == (120, 90)
    assert data["width_metres"] == 6.0


def test_mapping_inspect_missing_image(runner, tmp_path):
    map_yaml = write_map(tmp_path, image="gone.png")

    result = runner.invoke(app, ["mapping", "inspect", str(map_yaml), "--json"])
    assert result.exit_code == 1
    data = json.loads(result.output)
    assert data["image_exists"] is False
    assert data["width"] is None
    assert data["width_metres"] is None

    result = runner.invoke(app, ["mapping", "inspect", str(map_yaml)])
    assert result.exit_code == 1
    assert "The map image is missing" in all_output(result)


def test_mapping_inspect_missing_file(runner, tmp_path):
    result = runner.invoke(app, ["mapping", "inspect", str(tmp_path / "nope.yaml")])
    assert result.exit_code == 1
    assert "Map file not found:" in all_output(result)


def test_mapping_inspect_bad_yaml(runner, tmp_path):
    not_a_map = tmp_path / "list.yaml"
    not_a_map.write_text("- one\n- two\n", encoding="utf-8")
    result = runner.invoke(app, ["mapping", "inspect", str(not_a_map)])
    assert result.exit_code == 1
    assert "Not a readable map YAML" in all_output(result)
    assert "does not contain a mapping" in all_output(result)


def test_mapping_run_starts_tracked_run(runner, fake_ros_world, tmp_path, monkeypatch):
    runs_base = configure_runs(tmp_path, monkeypatch)
    fake_ros_world.packages("isaac_ros_nvblox")
    result = runner.invoke(app, ["mapping", "run", "--name", "nvblox"])
    assert result.exit_code == 0, all_output(result)
    run_dir = wait_for_run(runs_base)
    manifest = yaml.safe_load((run_dir / "manifest.yaml").read_text(encoding="utf-8"))
    assert manifest["kind"] == "mapping"
    assert manifest["name"] == "nvblox"
    assert manifest["command"][-2:] == ["isaac_ros_nvblox", "nvblox.launch.py"]
    stdout = (run_dir / "stdout.log").read_text(encoding="utf-8")
    assert stdout.strip() == "launch isaac_ros_nvblox nvblox.launch.py"


def test_mapping_run_needs_launch_file(runner, fake_ros_world):
    fake_ros_world.packages("nav2_map_server")
    result = runner.invoke(app, ["mapping", "run", "--backend", "map_saver"])
    assert result.exit_code == 1
    assert "No launch file is defined for 'map_saver' in domain 'mapping'." in all_output(result)


def test_mapping_status(runner, fake_ros_world):
    fake_ros_world.packages("isaac_ros_nvblox")
    result = runner.invoke(app, ["mapping", "status", "--json"])
    assert result.exit_code == 0, all_output(result)
    data = json.loads(result.output)
    assert data["domain"] == "mapping"
    assert data["total"] == 3
    assert data["installed"] == 1
    assert data["running"] == []
    states = {item["key"]: item for item in data["capabilities"]}
    assert states["nvblox"]["found"] is True
    assert states["map_saver"]["core"] is True
    assert states["map_saver"]["found"] is False

    result = runner.invoke(app, ["mapping", "status"])
    assert result.exit_code == 0, all_output(result)
    assert "1 of 3 capabilities installed." in result.output
